[phases.setup]
nixPkgs = ['python39', 'python39Packages.pip', 'python39Packages.virtualenv']

[phases.install]
cmds = [
  'python -m venv /opt/venv',
  '/opt/venv/bin/pip install --upgrade pip',
  'cd backend && /opt/venv/bin/pip install -r requirements.txt'
]

[start]
cmd = 'cd backend && /opt/venv/bin/python -m uvicorn server:app --host 0.0.0.0 --port $PORT'
