[phases.setup]
nixPkgs = ['python39']

[phases.install]
cmds = [
  'cd backend && pip install --user fastapi uvicorn[standard] pymongo python-jose[cryptography] passlib[bcrypt] python-multipart python-dotenv',
  'cd backend && pip install --user -r requirements.txt'
]

[start]
cmd = 'cd backend && /root/.local/bin/uvicorn server:app --host 0.0.0.0 --port $PORT'
