[phases.setup]
nixPkgs = ['python39', 'pip']

[phases.install]
cmds = ['cd backend && pip install -r requirements.txt']

[phases.build]
cmds = ['echo "No build phase needed"']

[start]
cmd = 'cd backend && python -m uvicorn server:app --host 0.0.0.0 --port $PORT'
